### PR TITLE
Add Vapor Nation

### PR DESCRIPTION
**Pull request by twof**
- **Project Name**: Vapor Nation
- **Project URL**: https://twof.github.io/VaporNation/
- **Project Description**: Weekly Vapor newsletter, updated every Monday
- **Why it should be added to `awesome-vapor`**: It's the best way to keep up with Vapor while it's in beta and beyond!
- [x] Runs using lates Vapor
- [x] Updated **contents.json** instead of README

### CODE REVIEW

**Comment by syky27** [comment]
Hi, It needs to pass the build for me to merge it. Unfortunately I currently don't have time to go through the build log and find out why it failed, could you? Thanks.

**Comment by twof** [comment]
@syky27 
```
The command "awesome_bot contents.json -w AERecord" exited with 1.
0.23s$ json validate --schema-file=.github/schema.json --document-file=contents.json
```

I'm not entirely sure how to read the Travis logs, but I think that's it, although I put content.json through another linter, and it's not finding any issues. 

Looks like it could also be an ongoing issue with Travis
https://github.com/travis-ci/travis-ci/issues/8507

**Comment by syky27** [comment]
Ok, so there were some errors due URL change...

**Comment by syky27** [comment]
Thank you, and sorry for it to take that long...

**Pull request merged**
